export const GET_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS"
export const GET_CONTACTS_FAILURE = "GET_CONTACTS_FAILURE"
export const GET_CONTACTS_START = "GET_CONTACTS_START"

export const REQUEST_CONTACTS = "REQUEST_CONTACTS"

export const PATCH_CONTACTS_SUCCESS = "GET_CONTACTS_SUCCESS"
export const PATCH_CONTACTS_FAILURE = "GET_CONTACTS_FAILURE"
export const PATCH_CONTACTS_START = "GET_CONTACTS_START"